itemModelLoc: tachyon://localhost:19998/item-model
userModelLoc: tachyon://localhost:19998/user-model
ratingsLoc: tachyon://localhost:19998/movie-ratings
matPredictionsLoc: tachyon://localhost:19998/mat-predictions
numFactors: 50
