itemModelLoc: tachyon://ec2-54-87-239-99.compute-1.amazonaws.com:19998/item-model
userModelLoc: tachyon://ec2-54-87-239-99.compute-1.amazonaws.com:19998/user-model
ratingsLoc: tachyon://ec2-54-87-239-99.compute-1.amazonaws.com:19998/movie-ratings
matPredictionsLoc: tachyon://ec2-54-87-239-99.compute-1.amazonaws.com:19998/mat-predictions
numFactors: 50
