#ec2-184-73-72-139.compute-1.amazonaws.com 

modelStorage:
    storageType: tachyon
    address: tachyon://ec2-204-236-207-142.compute-1.amazonaws.com:19998
    items: item-model
    users: user-model
    ratings: movie-ratings

#modelStorage:
#    storageType: local
#    ratings: /Users/crankshaw/code/amplab/model-serving/data/ml-100k/u.data
#    users: /Users/crankshaw/code/amplab/model-serving/data/trained_50_features/all_users_clean_50.txt
#    items: /Users/crankshaw/code/amplab/model-serving/data/trained_50_features/all_products_clean_50.txt

#modelStorage:
#    storageType: cassandra
#    address: 127.0.0.1
#    keyspace: velox
#    items: items
#    users: users
#    ratings: ratings

# itemModelLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/item-model
# userModelLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/user-model
# ratingsLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/movie-ratings
sparkMaster: spark://ec2-54-92-229-50.compute-1.amazonaws.com:7077

# matPredictionsLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/mat-predictions
numFactors: 50
logging:
  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/velox.log
      archivedLogFilenamePattern: ./logs/velox-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: WARN
      target: stderr

server:
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ./logs/requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ./logs/requests.%d.log.gz
        archivedFileCount: 5
