hostname: none
logging:
  appenders:
  - archivedFileCount: 5
    archivedLogFilenamePattern: /home/ubuntu/velox-modelserver/logs/velox-%d.log.gz
    currentLogFilename: /home/ubuntu/velox-modelserver/logs/velox.log
    timeZone: UTC
    type: file
  - target: stderr
    threshold: INFO
    type: console
models:
  newsgroups:
    cacheFeatures: false
    cachePartialSums: false
    cachePredictions: false
    modelLoc: /home/ubuntu/velox-modelserver/data/news-classifier-from-tomer
    modelSize: 20
    modelType: NewsgroupsModel
    partitionFile: /home/ubuntu/velox-modelserver/conf/server_partitions.txt
    storage:
      ratings:
        docLength: 200
        ngramFile: /home/ubuntu/velox-modelserver/data/20_news_ngrams.txt
        numItems: 100
        numPartitions: 3
        percentOfItems: 80.0
        storageType: jvmRandomDocs
        totalNumUsers: 1000
      users:
        numPartitions: 3
        storageType: jvmRandomUsers
        totalNumUsers: 1000
server:
  applicationConnectors:
  - acceptQueueSize: 4096
    port: 8080
    type: http
  requestLog:
    appenders:
    - archive: true
      archivedFileCount: 5
      archivedLogFilenamePattern: /home/ubuntu/velox-modelserver/logs/requests.%d.log.gz
      currentLogFilename: /home/ubuntu/velox-modelserver/logs/requests.log
      threshold: INFO
      type: file
    timeZone: UTC
sparkMaster: spark://ec2-54-92-229-50.compute-1.amazonaws.com:7077
