#ec2-184-73-72-139.compute-1.amazonaws.com 

tachyonMaster: tachyon://ec2-54-92-249-238.compute-1.amazonaws.com:19998
itemStoreName: item-model
userStoreName: user-model
ratingsStoreName: movie-ratings

# itemModelLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/item-model
# userModelLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/user-model
# ratingsLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/movie-ratings
sparkMaster: spark://ec2-54-242-32-12.compute-1.amazonaws.com:7077

# matPredictionsLoc: tachyon://ec2-184-73-72-139.compute-1.amazonaws.com:19998/mat-predictions
numFactors: 50
logging:
  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/velox.log
      archivedLogFilenamePattern: ./logs/velox-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: INFO
      target: stderr
    
server:
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: ./logs/requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: ./logs/requests.%d.log.gz
        archivedFileCount: 5
